CREATE TABLE `events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(255) NOT NULL,
	`slug` varchar(255) NOT NULL,
	`description` text,
	`eventDate` timestamp NOT NULL,
	`endDate` timestamp,
	`locationName` varchar(255) NOT NULL,
	`address` varchar(500),
	`city` varchar(100) NOT NULL,
	`category` enum('show','festa','gastronomia','esporte','cultura') NOT NULL,
	`priceCents` int NOT NULL DEFAULT 0,
	`sourceUrl` varchar(1000),
	`imageUrl` varchar(1000),
	`latitude` varchar(32),
	`longitude` varchar(32),
	`sourceHash` varchar(64),
	`isPublished` int NOT NULL DEFAULT 1,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `events_id` PRIMARY KEY(`id`),
	CONSTRAINT `events_slug_unique` UNIQUE(`slug`),
	CONSTRAINT `events_sourceHash_unique` UNIQUE(`sourceHash`)
);
