import { AlertTriangle, CheckCircle2, Clock3, Loader2, MapPin, RefreshCw, XCircle } from "lucide-react";
import { trpc } from "@/lib/trpc";

const sourceLabels = { public: "Fontes públicas", instagram: "Instagram", ingresse: "Ingresse", instagram_agenda_weekend: "Instagram — Agenda da Semana" } as const;
const labelForSource = (sourceKey: string) => sourceLabels[sourceKey as keyof typeof sourceLabels] ?? sourceKey;
const reprocessSources = ["public", "instagram"] as const;

export default function AdminReportsPanel() {
  const report = trpc.ingestionReports.summary.useQuery(undefined, { refetchInterval: 30_000 });
  const geocoding = trpc.ingestionReports.geocoding.useQuery(undefined, { refetchInterval: 30_000 });
  const reprocess = trpc.ingestionReports.reprocess.useMutation({ onSuccess: () => report.refetch(), onError: () => report.refetch() });
  const geocodeNow = trpc.ingestionReports.geocodeNow.useMutation({ onSuccess: () => geocoding.refetch() });
  const data = report.data;
  const metaStatus = data?.metaStatus?.status ?? "never";
  const metaStatusCopy = {
    active: { label: "Operacional", tone: "border-emerald-300/30 bg-emerald-300/10 text-emerald-100", icon: CheckCircle2 },
    degraded: { label: "Degradada", tone: "border-yellow-300/30 bg-yellow-300/10 text-yellow-100", icon: AlertTriangle },
    failed: { label: "Com falha", tone: "border-red-300/30 bg-red-300/10 text-red-100", icon: XCircle },
    never: { label: "Ainda não sincronizada", tone: "border-white/10 bg-white/[0.03] text-zinc-300", icon: Clock3 },
  }[metaStatus];
  const MetaIcon = metaStatusCopy.icon;
  const formatSyncDate = (value: string | null | undefined) => value ? new Date(value).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" }) : "Nenhuma sincronização bem-sucedida registrada";
  const cards = [
    { label: "Sucesso", value: data?.totals.succeeded ?? 0, icon: CheckCircle2, tone: "text-emerald-300" },
    { label: "Falhas", value: data?.totals.failed ?? 0, icon: XCircle, tone: "text-red-300" },
    { label: "Parciais", value: data?.totals.partial ?? 0, icon: AlertTriangle, tone: "text-yellow-200" },
    { label: "Importados", value: data?.totals.imported ?? 0, icon: MapPin, tone: "text-cyan-300" },
  ];
  return <section aria-labelledby="reports-heading" className="mt-6 rounded-3xl border border-white/10 bg-white/[0.04] p-5 sm:p-7">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
      <div><p className="text-xs font-black uppercase tracking-[0.2em] text-yellow-200">Observabilidade</p><h2 id="reports-heading" className="mt-1 text-xl font-black">Relatórios operacionais</h2><p className="mt-1 text-sm text-zinc-400">Acompanhe a saúde da ingestão e reexecute uma fonte sem duplicar eventos.</p></div>
      <button type="button" onClick={() => report.refetch()} aria-label="Atualizar relatórios" className="inline-flex items-center gap-2 self-start rounded-xl border border-white/10 px-3 py-2 text-xs font-bold text-zinc-200 hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-yellow-300"><RefreshCw size={15} /> Atualizar</button>
    </div>
    <div className="mt-5 grid gap-3 sm:grid-cols-4">{cards.map(item => <div key={item.label} className="rounded-2xl border border-white/10 bg-black/10 p-4"><item.icon size={17} className={item.tone} /><p className="mt-3 text-2xl font-black">{item.value}</p><p className="text-xs text-zinc-500">{item.label}</p></div>)}</div>
    <div className={`mt-5 rounded-2xl border p-4 ${metaStatusCopy.tone}`} aria-live="polite" data-testid="meta-integration-status">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex items-start gap-3"><MetaIcon size={19} className="mt-0.5 shrink-0" /><div><p className="text-xs font-black uppercase tracking-[0.16em] opacity-80">Integração Meta</p><h3 className="mt-1 text-lg font-black">{metaStatusCopy.label}</h3><p className="mt-1 text-xs opacity-75">Status baseado nas execuções oficiais persistidas, sem dados simulados.</p></div></div>
        <div className="rounded-xl border border-current/20 bg-black/10 px-3 py-2 text-left sm:min-w-64"><p className="text-[11px] font-bold uppercase tracking-wide opacity-70">Última sincronização bem-sucedida</p><p className="mt-1 text-sm font-black">{formatSyncDate(data?.metaStatus?.lastSuccessfulSync)}</p></div>
      </div>
    </div>
    <div className="mt-5 rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">Tendência dos últimos 7 dias</h3><p className="mt-1 text-xs text-zinc-500">Execuções reais registradas; a escala usa o maior volume diário observado.</p></div><span className="text-xs text-zinc-500">São Paulo</span></div><div className="mt-5 grid grid-cols-7 items-end gap-2" aria-label="Gráfico semanal de ingestão"><div className="sr-only">{(data?.weeklyTrend ?? []).map(day => `${day.label}: ${day.receivedPosts} posts recebidos, ${day.approvedPosts} aprovados, ${day.structuredEvents} estruturados e ${day.imported} importados`).join("; ")}</div>{(data?.weeklyTrend ?? []).map(day => { const max = Math.max(...(data?.weeklyTrend ?? []).map(item => Math.max(item.receivedPosts, item.imported, item.runs)), 1); const height = Math.max(8, Math.round((Math.max(day.receivedPosts, day.imported, day.runs) / max) * 100)); return <div key={day.date} className="min-w-0 text-center"><div className="flex h-28 items-end justify-center rounded-lg bg-white/[0.03] px-1"><div className="w-full rounded-t-md bg-gradient-to-t from-orange-400 to-yellow-200" style={{ height: `${height}%` }} title={`${day.label}: ${day.receivedPosts} posts, ${day.imported} importados`} /></div><p className="mt-2 text-[10px] font-bold text-zinc-400">{day.label}</p><p className="text-[10px] text-zinc-600">{day.runs} exec.</p></div>; })}</div><div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-5"><span>Posts: <strong>{(data?.weeklyTrend ?? []).reduce((sum, day) => sum + day.receivedPosts, 0)}</strong></span><span>Aprovados: <strong>{(data?.weeklyTrend ?? []).reduce((sum, day) => sum + day.approvedPosts, 0)}</strong></span><span>Estruturados: <strong>{(data?.weeklyTrend ?? []).reduce((sum, day) => sum + day.structuredEvents, 0)}</strong></span><span>Importados: <strong>{(data?.weeklyTrend ?? []).reduce((sum, day) => sum + day.imported, 0)}</strong></span><span>Sem mídia: <strong className="text-yellow-200">{(data?.weeklyTrend ?? []).reduce((sum, day) => sum + day.zeroMediaRuns, 0)}</strong></span></div></div>
    <div className="mt-5 rounded-2xl border border-cyan-300/20 bg-cyan-300/5 p-4" data-testid="weekly-operational-summary"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-black">Resumo operacional semanal</h3><p className="mt-1 text-xs text-zinc-400">Reconciliação determinística das execuções dos últimos 7 dias.</p></div><span className="text-xs text-zinc-500">Sem dados sensíveis</span></div><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4"><div><p className="text-lg font-black text-cyan-200">{data?.weeklySummary.retries ?? 0}</p><p className="text-xs text-zinc-500">Retries</p></div><div><p className="text-lg font-black text-fuchsia-200">{data?.weeklySummary.fallbackList ?? 0}</p><p className="text-xs text-zinc-500">Fallback para lista</p></div><div><p className="text-lg font-black text-yellow-200">{data?.weeklySummary.duplicates ?? 0}</p><p className="text-xs text-zinc-500">Duplicidades</p></div><div><p className="text-lg font-black text-orange-200">{(data?.weeklySummary.missingCoordinates ?? 0) + (data?.weeklySummary.outOfBoundsCoordinates ?? 0)}</p><p className="text-xs text-zinc-500">Coordenadas inválidas</p></div></div><p className="mt-4 text-xs text-zinc-500">{data?.weeklySummary.degradedRuns ?? 0} execuções degradadas · {data?.weeklySummary.inconsistentRuns ?? 0} reconciliações inconsistentes.</p></div>
    <div className="mt-5 rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-black">Eventos ingeridos por fonte</h3><p className="mt-1 text-xs text-zinc-500">Totais acumulados nas execuções registradas, sem dados simulados.</p></div><span className="text-xs text-zinc-500">Atualiza a cada 30 s</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{data?.sourceMetrics.map(source => <div key={source.sourceKey} className="rounded-xl border border-white/10 bg-white/[0.03] p-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-bold">{labelForSource(source.sourceKey)}</p><span className="text-lg font-black text-cyan-200">{source.imported}</span></div><p className="mt-1 text-xs text-zinc-500">{source.runs} execuções · {source.failed} falhas</p></div>)}</div>{(data?.sourceMetrics.length ?? 0) === 0 && <p className="mt-4 text-sm text-zinc-500">Ainda não há métricas por fonte.</p>}</div>
    <div className="mt-5 rounded-2xl border border-white/10 bg-black/10 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-bold">Fila de geocodificação</p><p className="mt-1 text-xs text-zinc-500">Eventos do Instagram são processados em lotes para manter a ingestão segura.</p></div><button type="button" onClick={() => geocodeNow.mutate()} disabled={geocodeNow.isPending || (geocoding.data?.pending ?? 0) === 0} className="inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-3 py-2 text-xs font-black text-zinc-950 disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-cyan-200">{geocodeNow.isPending && <Loader2 size={14} className="animate-spin" />} Processar agora</button></div><div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><span>Pendentes: <strong>{geocoding.data?.pending ?? 0}</strong></span><span>Processando: <strong>{geocoding.data?.processing ?? 0}</strong></span><span>Concluídos: <strong>{geocoding.data?.succeeded ?? 0}</strong></span><span>Falhos: <strong>{geocoding.data?.failed ?? 0}</strong></span></div></div>
    <div className="mt-5"><h3 className="mb-2 text-sm font-black">Reprocessar fonte</h3><div className="grid gap-2 sm:grid-cols-2">{reprocessSources.map(source => <button key={source} type="button" onClick={() => reprocess.mutate({ sourceKey: source })} disabled={reprocess.isPending} className="inline-flex items-center justify-between rounded-xl border border-white/10 px-4 py-3 text-left text-sm font-bold text-zinc-200 hover:bg-white/10 disabled:opacity-40 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-orange-300"><span>{sourceLabels[source]}</span>{reprocess.isPending ? <Loader2 size={15} className="animate-spin" /> : <RefreshCw size={15} />}</button>)}</div></div>
    <div className="mt-5 overflow-x-auto rounded-2xl border border-white/10"><table className="w-full min-w-[620px] text-left text-xs"><caption className="sr-only">Últimas execuções de ingestão</caption><thead className="bg-white/5 text-zinc-400"><tr><th className="px-4 py-3">Rotina</th><th className="px-4 py-3">Fonte</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Importados</th><th className="px-4 py-3">Início</th></tr></thead><tbody className="divide-y divide-white/10">{data?.runs.map(run => <tr key={run.id}><td className="px-4 py-3 font-bold">{run.routine}</td><td className="px-4 py-3 text-zinc-400">{run.sourceKey ?? "—"}</td><td className="px-4 py-3"><span className={run.status === "succeeded" ? "text-emerald-300" : run.status === "failed" ? "text-red-300" : "text-yellow-200"}>{run.status}</span></td><td className="px-4 py-3">{run.importedCount}</td><td className="px-4 py-3 text-zinc-400">{new Date(run.startedAt).toLocaleString("pt-BR")}</td></tr>)}</tbody></table>{data?.runs.length === 0 && <p className="px-4 py-5 text-sm text-zinc-500">Ainda não há execuções registradas.</p>}</div>
    <div className="mt-5 rounded-2xl border border-red-300/30 bg-red-300/10 p-4" aria-live="polite"><div className="flex items-center gap-2"><AlertTriangle size={16} className="text-red-200" /><h3 className="text-sm font-black text-red-100">Alertas críticos de ingestão</h3></div>{data?.criticalAlerts.slice(0, 5).map(alert => <div key={`critical-${alert.id}`} className="mt-3 rounded-xl border border-red-200/20 bg-black/10 px-4 py-3"><p className="text-sm font-bold text-red-100">{alert.title}</p><p className="mt-1 text-xs text-red-100/70">{alert.message}</p></div>)}{data?.criticalAlerts.length === 0 && <p className="mt-2 text-sm text-red-100/70">Nenhum timeout ou HTTP 5xx pendente.</p>}</div>
    <div className="mt-5"><h3 className="mb-2 text-sm font-black">Alertas recentes</h3>{data?.alerts.slice(0, 5).map(alert => <div key={alert.id} className="mb-2 rounded-xl border border-red-300/15 bg-red-300/5 px-4 py-3"><div className="flex items-center justify-between gap-3"><p className="text-sm font-bold text-red-100">{alert.title}</p><span className="text-[11px] uppercase text-zinc-500">{alert.integration}</span></div><p className="mt-1 text-xs text-zinc-400">{alert.message}</p></div>)}{data?.alerts.length === 0 && <p className="text-sm text-zinc-500">Nenhum alerta registrado.</p>}</div>
  </section>;
}
