import React, { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Clock3, Edit3, Loader2, RefreshCw, Trash2, XCircle } from "lucide-react";
import { toast as sonnerToast } from "sonner";
import { trpc } from "@/lib/trpc";
import { friendlyAdminErrorMessage } from "@/lib/adminFeedback";
import { Button } from "@/components/ui/button";
import { ManualReviewEditDialog } from "./ManualReviewEditDialog";
import { ManualReviewFilters, PAGE_SIZES } from "./ManualReviewFilters";
import { applyRawTokenToDateTime, draftFromEvent, formatDate, getRawTextHighlightSegments, highlightRawText, localDateTimeToIso, sourceLabel, statusClass, statusLabel, toDateTimeLocal, type ManualReviewDraft, type ManualReviewEvent, type ManualReviewStatus, type RawTextToken } from "./manual-review-shared";

export { applyRawTokenToDateTime, draftFromEvent, getRawTextHighlightSegments, highlightRawText, localDateTimeToIso, toDateTimeLocal };
export type { ManualReviewDraft, ManualReviewEvent, ManualReviewStatus, RawTextToken };

function readUrlValue(key: string) { if (typeof window === "undefined") return ""; return new URLSearchParams(window.location.search).get(key) ?? ""; }
function validStatus(value: string): value is ManualReviewStatus { return value === "pending" || value === "approved" || value === "rejected" || value === "expired"; }

export default function ManualReviewPanel() {
  const [status, setStatus] = useState<"" | ManualReviewStatus>(() => { const value = readUrlValue("manual_review_status"); return validStatus(value) ? value : "pending"; });
  const [sourceType, setSourceType] = useState(() => readUrlValue("manual_review_source"));
  const [from, setFrom] = useState(() => readUrlValue("manual_review_from"));
  const [to, setTo] = useState(() => readUrlValue("manual_review_to"));
  const [pageSize, setPageSize] = useState(() => { const value = Number(readUrlValue("manual_review_page_size")); return PAGE_SIZES.includes(value as typeof PAGE_SIZES[number]) ? value : 25; });
  const [page, setPage] = useState(0);
  const [selectedEvent, setSelectedEvent] = useState<ManualReviewEvent | null>(null);
  const [selectedIds, setSelectedIds] = useState<number[]>([]);
  const [draft, setDraft] = useState<ManualReviewDraft | null>(null);
  const [copyState, setCopyState] = useState<"idle" | "copied" | "error">("idle");
  const [copiedToken, setCopiedToken] = useState<string | null>(null);
  const [appliedToken, setAppliedToken] = useState<string | null>(null);

  const listInput = useMemo(() => ({ status: status || undefined, sourceType: sourceType.trim() || undefined, from: from || undefined, to: to || undefined, offset: page * pageSize, limit: pageSize }), [status, sourceType, from, to, page, pageSize]);
  const queueQuery = trpc.adminRoutine.manualReview.list.useQuery(listInput, { refetchInterval: 30_000 });
  const metricsQuery = trpc.adminRoutine.manualReview.metrics.useQuery(undefined, { refetchInterval: 30_000 });
  const expireStaleHighlightsMutation = trpc.adminRoutine.manualReview.expireStaleHighlights.useMutation({ onSuccess: result => { sonnerToast.success("Destaques antigos expirados", { description: `${result.expiredCount} entrada(s) foram removidas da fila de revisão.` }); void queueQuery.refetch(); void metricsQuery.refetch(); }, onError: error => sonnerToast.error("Não foi possível expirar destaques", { description: friendlyAdminErrorMessage(error, "Tente novamente em instantes.") }) });
  const closeEditor = () => { setSelectedEvent(null); setDraft(null); };
  const updateMutation = trpc.adminRoutine.manualReview.update.useMutation({ onSuccess: updated => { setSelectedEvent(updated); setDraft(draftFromEvent(updated)); sonnerToast.success("Revisão salva", { description: "Os dados assistidos foram atualizados." }); void queueQuery.refetch(); void metricsQuery.refetch(); }, onError: error => sonnerToast.error("Não foi possível salvar a revisão", { description: friendlyAdminErrorMessage(error, "Revise os campos e tente novamente.") }) });
  const approveMutation = trpc.adminRoutine.manualReview.approve.useMutation({ onSuccess: approved => { setSelectedEvent(approved); setDraft(draftFromEvent(approved)); showUndoToast(approved.id, "Evento publicado"); void queueQuery.refetch(); void metricsQuery.refetch(); }, onError: error => sonnerToast.error("Não foi possível publicar", { description: friendlyAdminErrorMessage(error, "Preencha data, local, cidade e categoria antes de aprovar.") }) });
  const approveManyMutation = trpc.adminRoutine.manualReview.approveMany.useMutation({ onSuccess: result => { setSelectedIds(current => current.filter(id => !result.ids.includes(id))); sonnerToast.success("Eventos publicados", { description: `${result.count} evento(s) foram aprovados e publicados.`, duration: 8_000, action: { label: "Desfazer", onClick: () => undoManyMutation.mutate({ ids: result.ids }) } }); void queueQuery.refetch(); void metricsQuery.refetch(); }, onError: error => sonnerToast.error("Não foi possível aprovar em massa", { description: friendlyAdminErrorMessage(error, "Complete os campos obrigatórios dos eventos selecionados.") }) });
  const rejectManyMutation = trpc.adminRoutine.manualReview.rejectMany.useMutation({ onSuccess: result => { setSelectedIds(current => current.filter(id => !result.ids.includes(id))); sonnerToast.success("Eventos rejeitados", { description: `${result.count} evento(s) foram removidos da fila de revisão.`, duration: 8_000, action: { label: "Desfazer", onClick: () => undoManyMutation.mutate({ ids: result.ids }) } }); void queueQuery.refetch(); void metricsQuery.refetch(); }, onError: error => sonnerToast.error("Não foi possível rejeitar em massa", { description: friendlyAdminErrorMessage(error, "Tente novamente em instantes.") }) });
  const rejectMutation = trpc.adminRoutine.manualReview.reject.useMutation({ onSuccess: rejected => { setSelectedEvent(rejected); setDraft(draftFromEvent(rejected)); showUndoToast(rejected.id, "Evento rejeitado"); void queueQuery.refetch(); void metricsQuery.refetch(); }, onError: error => sonnerToast.error("Não foi possível rejeitar", { description: friendlyAdminErrorMessage(error, "Tente novamente em instantes.") }) });
  const undoMutation = trpc.adminRoutine.manualReview.undo.useMutation({ onSuccess: restored => { setSelectedEvent(restored); setDraft(draftFromEvent(restored)); sonnerToast.success("Ação desfeita", { description: "O evento voltou para a fila de revisão manual." }); void queueQuery.refetch(); void metricsQuery.refetch(); }, onError: error => sonnerToast.error("Não foi possível desfazer", { description: friendlyAdminErrorMessage(error, "A ação já pode ter sido revertida ou expirado o prazo.") }) });
  const undoManyMutation = trpc.adminRoutine.manualReview.undoMany.useMutation({ onSuccess: result => { sonnerToast.success("Ações desfeitas", { description: `${result.count} evento(s) voltaram para a fila de revisão.` }); void queueQuery.refetch(); void metricsQuery.refetch(); }, onError: error => sonnerToast.error("Não foi possível desfazer", { description: friendlyAdminErrorMessage(error, "Algumas ações já podem ter expirado.") }) });
  function showUndoToast(id: number, message: string) { sonnerToast.success(message, { description: "Você pode reverter esta ação rapidamente.", duration: 8_000, action: { label: "Desfazer", onClick: () => undoMutation.mutate({ id }) } }); }

  useEffect(() => { setPage(0); if (typeof window === "undefined") return; const params = new URLSearchParams(window.location.search); if (status) params.set("manual_review_status", status); else params.delete("manual_review_status"); if (sourceType.trim()) params.set("manual_review_source", sourceType.trim()); else params.delete("manual_review_source"); if (from) params.set("manual_review_from", from); else params.delete("manual_review_from"); if (to) params.set("manual_review_to", to); else params.delete("manual_review_to"); params.set("manual_review_page_size", String(pageSize)); window.history.replaceState({}, "", `${window.location.pathname}${params.toString() ? `?${params.toString()}` : ""}${window.location.hash}`); }, [status, sourceType, from, to, pageSize]);
  useEffect(() => { setPage(0); }, [status, sourceType, from, to, pageSize]);

  const pendingVisibleIds = useMemo(() => (queueQuery.data?.items ?? []).filter(event => event.status === "pending").map(event => event.id), [queueQuery.data?.items]);
  const pendingVisibleKey = pendingVisibleIds.join(",");
  useEffect(() => { setSelectedIds(current => current.filter(id => pendingVisibleIds.includes(id))); }, [pendingVisibleKey]);
  const allPendingSelected = pendingVisibleIds.length > 0 && pendingVisibleIds.every(id => selectedIds.includes(id));
  const bulkPending = approveManyMutation.isPending || rejectManyMutation.isPending;
  const toggleAllPending = () => setSelectedIds(current => allPendingSelected ? current.filter(id => !pendingVisibleIds.includes(id)) : Array.from(new Set([...current, ...pendingVisibleIds])));
  const toggleSelected = (id: number) => setSelectedIds(current => current.includes(id) ? current.filter(selectedId => selectedId !== id) : [...current, id]);
  const approveSelectedMany = () => { if (!bulkPending && selectedIds.length > 0) approveManyMutation.mutate({ ids: Array.from(new Set(selectedIds)) }); };
  const rejectSelectedMany = () => { if (!bulkPending && selectedIds.length > 0 && window.confirm(`Rejeitar ${selectedIds.length} evento(s) selecionado(s)? Eles sairão da fila de revisão.`)) rejectManyMutation.mutate({ ids: Array.from(new Set(selectedIds)) }); };
  const selectEvent = (event: ManualReviewEvent) => { setSelectedEvent(event); setDraft(draftFromEvent(event)); setCopyState("idle"); setCopiedToken(null); setAppliedToken(null); };
  const copyRawText = async () => { if (!draft?.rawText) return; try { await navigator.clipboard.writeText(draft.rawText); setCopyState("copied"); sonnerToast.success("Texto copiado", { description: "O texto original foi copiado para a área de transferência." }); } catch { setCopyState("error"); sonnerToast.error("Não foi possível copiar", { description: "Selecione o texto manualmente e tente novamente." }); } };
  const copyToken = async (token: RawTextToken) => { try { await navigator.clipboard.writeText(token.value); setCopiedToken(token.value); sonnerToast.success("Token copiado", { description: `“${token.value}” foi copiado.` }); } catch { sonnerToast.error("Não foi possível copiar o token", { description: "Selecione o valor manualmente e tente novamente." }); } };
  const setDraftField = <K extends keyof ManualReviewDraft>(key: K, value: ManualReviewDraft[K]) => setDraft(current => current ? { ...current, [key]: value } : current);
  const applyTokenToDraft = (token: RawTextToken) => { if (!draft) return; const nextEventDate = applyRawTokenToDateTime(draft.eventDate, token); if (!nextEventDate) { sonnerToast.info("Token não reconhecido para preenchimento", { description: "O valor foi mantido disponível para cópia manual; confirme a data ou horário no formulário." }); return; } setDraft(current => current ? { ...current, eventDate: nextEventDate } : current); setAppliedToken(token.value); sonnerToast.success("Token aplicado", { description: `“${token.value}” foi aplicado à data e hora do evento.` }); };
  const saveDraft = () => { if (!selectedEvent || !draft || updateMutation.isPending) return; updateMutation.mutate({ id: selectedEvent.id, title: draft.title, eventDate: localDateTimeToIso(draft.eventDate), endDate: localDateTimeToIso(draft.endDate), locationName: draft.locationName || null, address: draft.address || null, city: draft.city || null, category: draft.category || null, genre: draft.genre || null, summary: draft.summary || null, priceCents: draft.priceCents ? Number(draft.priceCents) : null, sourceUrl: draft.sourceUrl || null, sourceType: draft.sourceType || null, imageUrl: draft.imageUrl || null, rawText: draft.rawText || null, reason: draft.reason }); };
  const approveSelected = () => { if (selectedEvent && !approveMutation.isPending) approveMutation.mutate({ id: selectedEvent.id }); };
  const rejectSelected = () => { if (selectedEvent && !rejectMutation.isPending) rejectMutation.mutate({ id: selectedEvent.id }); };
  const isSaving = updateMutation.isPending || approveMutation.isPending || rejectMutation.isPending || bulkPending;

  return <section className="mt-8 rounded-3xl border border-amber-300/20 bg-amber-300/[0.04] p-5 sm:p-7" data-testid="manual-review-panel" aria-labelledby="manual-review-title">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><Clock3 size={18} className="text-amber-200" /><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-200">Governança de eventos</p></div><h2 id="manual-review-title" className="mt-2 text-2xl font-black text-zinc-100">Fila de Revisão Manual</h2><p className="mt-1 max-w-2xl text-sm text-zinc-400">Eventos parcialmente estruturados pela IA permanecem aqui para completar os dados com segurança antes da publicação.</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" size="sm" onClick={() => { void queueQuery.refetch(); void metricsQuery.refetch(); }} disabled={queueQuery.isFetching || metricsQuery.isFetching || expireStaleHighlightsMutation.isPending} aria-label="Atualizar fila de revisão manual"><RefreshCw size={14} className={queueQuery.isFetching ? "animate-spin" : ""} /> Atualizar</Button><Button type="button" variant="outline" size="sm" onClick={() => expireStaleHighlightsMutation.mutate({})} disabled={expireStaleHighlightsMutation.isPending || queueQuery.isFetching} aria-busy={expireStaleHighlightsMutation.isPending} aria-label="Expirar destaques antigos pendentes">{expireStaleHighlightsMutation.isPending ? <Loader2 size={14} className="animate-spin" /> : <Trash2 size={14} />} {expireStaleHighlightsMutation.isPending ? "Expirando…" : "Expirar destaques antigos"}</Button></div></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2" data-testid="manual-review-metrics"><div className="rounded-2xl border border-emerald-300/20 bg-emerald-300/[0.06] p-4"><p className="text-xs font-bold uppercase tracking-wide text-emerald-200">Eventos publicados</p><p className="mt-2 text-3xl font-black text-emerald-50">{metricsQuery.data?.published ?? "—"}</p><p className="mt-1 text-xs text-zinc-500">Eventos ativos na agenda pública</p></div><div className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.06] p-4"><p className="text-xs font-bold uppercase tracking-wide text-amber-200">Aguardando revisão</p><p className="mt-2 text-3xl font-black text-amber-50">{metricsQuery.data?.awaitingReview ?? "—"}</p><p className="mt-1 text-xs text-zinc-500">Entradas incompletas preservadas pela IA</p></div></div>
    <ManualReviewFilters status={status} sourceType={sourceType} from={from} to={to} pageSize={pageSize} onStatusChange={setStatus} onSourceChange={setSourceType} onFromChange={setFrom} onToChange={setTo} onPageSizeChange={setPageSize} />
    <div className="mt-4 flex items-center justify-between text-xs text-zinc-500"><span>{queueQuery.data?.total ?? 0} entrada(s) para os filtros atuais</span>{queueQuery.isFetching && <span role="status">Atualizando…</span>}</div>
    {pendingVisibleIds.length > 0 && <div className="mt-3 flex flex-col gap-3 rounded-2xl border border-fuchsia-300/20 bg-fuchsia-300/[0.05] p-3 sm:flex-row sm:items-center sm:justify-between" data-testid="manual-review-bulk-actions"><label className="inline-flex min-h-11 items-center gap-2 text-xs font-bold text-zinc-200"><input type="checkbox" checked={allPendingSelected} onChange={toggleAllPending} disabled={bulkPending} aria-label="Selecionar todos os eventos pendentes visíveis" className="h-5 w-5 accent-fuchsia-400" /> Selecionar pendentes visíveis <span className="text-zinc-500">({pendingVisibleIds.length})</span></label>{selectedIds.length > 0 && <div className="flex flex-wrap items-center gap-2"><span className="text-xs font-black text-fuchsia-100">{selectedIds.length} selecionado(s)</span><Button type="button" size="sm" data-testid="manual-review-approve-many" onClick={approveSelectedMany} disabled={bulkPending} aria-busy={approveManyMutation.isPending} className="bg-emerald-300 text-zinc-950 hover:bg-emerald-200">{approveManyMutation.isPending ? <Loader2 size={14} className="animate-spin" /> : <CheckCircle2 size={14} />} {approveManyMutation.isPending ? "Publicando…" : "Aprovar selecionados"}</Button><Button type="button" variant="outline" size="sm" data-testid="manual-review-reject-many" onClick={rejectSelectedMany} disabled={bulkPending} aria-busy={rejectManyMutation.isPending} className="text-red-100">{rejectManyMutation.isPending ? <Loader2 size={14} className="animate-spin" /> : <XCircle size={14} />} {rejectManyMutation.isPending ? "Rejeitando…" : "Rejeitar selecionados"}</Button></div>}</div>}
    {queueQuery.isError ? <div className="mt-4 rounded-2xl border border-red-300/20 bg-red-300/[0.06] p-4 text-sm text-red-100">Não foi possível carregar a fila. <Button type="button" variant="outline" size="sm" className="ml-2" onClick={() => void queueQuery.refetch()}>Tentar novamente</Button></div> : queueQuery.data?.items.length ? <div className="mt-4 grid gap-3 lg:grid-cols-2" data-testid="manual-review-list">{queueQuery.data.items.map(event => <article key={event.id} className="grid gap-3 rounded-2xl border border-white/10 bg-zinc-950/40 p-3 sm:grid-cols-[96px_1fr]"><div>{event.imageUrl ? <img src={event.imageUrl} alt={`Imagem de ${event.title}`} loading="lazy" className="h-24 w-full rounded-xl border border-white/10 object-cover" /> : <div className="grid h-24 place-items-center rounded-xl border border-dashed border-white/10 text-center text-[11px] text-zinc-600">Sem imagem</div>}</div><div className="min-w-0"><div className="flex items-start justify-between gap-2"><div className="flex min-w-0 items-start gap-2">{event.status === "pending" && <input type="checkbox" checked={selectedIds.includes(event.id)} onChange={() => toggleSelected(event.id)} disabled={bulkPending} aria-label={`Selecionar ${event.title}`} className="mt-1 h-5 w-5 shrink-0 accent-fuchsia-400" />}<div className="min-w-0"><h3 className="truncate font-black text-zinc-100">{event.title}</h3><p className="mt-1 text-xs text-zinc-500">{sourceLabel(event.sourceType)} · {formatDate(event.eventDate)}</p></div></div><span className={`shrink-0 rounded-full px-2 py-1 text-[11px] font-black ${statusClass(event.status)}`}>{statusLabel(event.status)}</span></div><p className="mt-2 text-xs text-amber-100">Motivo: {event.reason}</p><p className="mt-2 line-clamp-2 text-xs text-zinc-400">{event.summary || event.rawText || "Sem texto complementar registrado."}</p><Button type="button" variant="outline" size="sm" data-testid={`manual-review-edit-${event.id}`} className="mt-3" onClick={() => selectEvent(event)}><Edit3 size={13} /> {event.status === "pending" ? "Completar e revisar" : "Ver detalhes"}</Button></div></article>)}</div> : <div className="mt-4 rounded-2xl border border-dashed border-white/10 p-6 text-center text-sm text-zinc-500">Nenhum evento encontrado para os filtros atuais.</div>}
    {(queueQuery.data?.hasNextPage || page > 0) && <div className="mt-5 flex items-center justify-between gap-3"><Button type="button" variant="outline" size="sm" onClick={() => setPage(current => Math.max(0, current - 1))} disabled={page === 0 || queueQuery.isFetching}>Anterior</Button><span className="text-xs text-zinc-500">Página {page + 1}</span><Button type="button" variant="outline" size="sm" onClick={() => setPage(current => current + 1)} disabled={!queueQuery.data?.hasNextPage || queueQuery.isFetching}>Próxima</Button></div>}
    <ManualReviewEditDialog event={selectedEvent} draft={draft} copyState={copyState} copiedToken={copiedToken} appliedToken={appliedToken} isSaving={isSaving} updatePending={updateMutation.isPending} approvePending={approveMutation.isPending} onClose={closeEditor} onCopyRawText={copyRawText} onCopyToken={copyToken} onApplyToken={applyTokenToDraft} onDraftField={setDraftField} onSave={saveDraft} onApprove={approveSelected} onReject={rejectSelected} />
  </section>;
}
